alg: PreferenceMAML
alg_kwargs:
  inner_lr: 0.001
  learn_inner_lr: true
  num_inner_steps: 2
  num_query: 24
  num_support: 24
batch_size: 4
checkpoint: null
collate_fn:
- import
- research.algs.maml
- collate
dataset: MultiTaskOracleFeedbackDataset
dataset_kwargs:
  batch_size: 48
  capacity: 100000
  discount: 0.99
  nstep: 1
  paths: datasets/reacher
  segment_size: 10
env: Goal_reacherReach_l2-v0
env_kwargs:
  task_kwargs:
    target_pos:
    - 0
    - 1
eval_env: null
eval_env_kwargs: {}
network: ActorCriticRewardPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers:
    - 256
    - 256
    log_std_bounds:
    - -5
    - 2
    ortho_init: true
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    ensemble_size: 2
    hidden_layers:
    - 256
    - 256
    ortho_init: true
  reward_class: MetaRewardMLPEnsemble
  reward_kwargs:
    act:
    - import
    - torch.nn.functional
    - leaky_relu
    ensemble_size: 3
    hidden_layers:
    - 256
    - 256
    - 256
    output_act:
    - import
    - torch.nn.functional
    - tanh
optim: Adam
optim_kwargs:
  lr: 0.0001
processor: null
processor_kwargs: {}
schedule: null
schedule_kwargs: {}
seed: null
train_kwargs:
  eval_fn: null
  eval_freq: 250
  log_freq: 100
  loss_metric: outer_loss
  max_eval_steps: 10
  total_steps: 100000
  workers: 0
validation_dataset_kwargs:
  capacity: 1000
  paths: datasets/reacher_valid
wrapper: null
wrapper_kwargs: {}
