# Example Config that uses almost all values

alg: PreferenceMAML
alg_kwargs:
  num_support: 32
  num_query: 32
  num_inner_steps: 2
  inner_lr: 0.001
  learn_inner_lr: True

optim: Adam
optim_kwargs:
  lr: 0.0001

network: ActorCriticRewardPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers: [256, 256, 256]
    log_std_bounds: [-5, 2]
    ortho_init: true
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [256, 256, 256]
    ensemble_size: 2
    ortho_init: true
  reward_class: RewardDiffusionDPO
  reward_kwargs:
    seglen: 24
    down_dims: [64, 128, 256]
    cond_predict_scale: False
    net_type: cond_unet

batch_size: 4
collate_fn: ["import", "research.algs.maml", "collate"]
checkpoint: null
seed: null

env: mw_sweep-into-v2

dataset: MultiTaskOracleFeedbackDataset
dataset_kwargs:
  paths: /home/cglossop/few-shot-preference-rl/datasets/mw/
  discount: 0.99
  nstep: 1
  batch_size: 64
  capacity: 6000
  segment_size: 24
validation_dataset_kwargs:
  paths: /home/cglossop/few-shot-preference-rl/datasets/mw_valid/
  capacity: 5000

processor: null

train_kwargs: # Arguments given to Algorithm.train
  total_steps: 200000 # The total number of steps to train
  log_freq: 1 # How often to log values
  eval_fn: null
  max_eval_steps: 10
  loss_metric: outer_loss # The validation metric that determines when to save the "best_checkpoint"
  workers: 0 # Number of dataloader workers.
  profile_freq: 50
